// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6VPUUThNBgR17n5_U9CTbgaPXwsFZEw',
    appId: '1:511003900438:web:ca6905a219f24b387f5337',
    messagingSenderId: '511003900438',
    projectId: 'movie-app-cd78c',
    authDomain: 'movie-app-cd78c.firebaseapp.com',
    storageBucket: 'movie-app-cd78c.appspot.com',
    measurementId: 'G-HN8CW2CFHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvTsMgrdsMszF9fw2PryASrjrzpiHCzM',
    appId: '1:511003900438:android:61deef8987fecbf37f5337',
    messagingSenderId: '511003900438',
    projectId: 'movie-app-cd78c',
    storageBucket: 'movie-app-cd78c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7kVDjt8Dmzph8Ccer7kmYpl9j6I0tbU',
    appId: '1:511003900438:ios:5165d3dc6148cf3d7f5337',
    messagingSenderId: '511003900438',
    projectId: 'movie-app-cd78c',
    storageBucket: 'movie-app-cd78c.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7kVDjt8Dmzph8Ccer7kmYpl9j6I0tbU',
    appId: '1:511003900438:ios:5ddaadf47d5d5b957f5337',
    messagingSenderId: '511003900438',
    projectId: 'movie-app-cd78c',
    storageBucket: 'movie-app-cd78c.appspot.com',
    iosBundleId: 'com.example.moviesapp.RunnerTests',
  );
}
